/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:667f079b-865a-4f74-9382-a7023bab011e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xAuPyU4oR",
    "aws_user_pools_web_client_id": "23u5e5e2mevlcvk731mgi07me8",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "cloudproject5c4c957d123e4212bbc91f33c07f9f86161432-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
